// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistrationTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registrationTest() {
    driver.get("https://www.greencity.cx.ua/#/greenCity");
    driver.manage().window().setSize(new Dimension(1536, 816));
    driver.findElement(By.cssSelector(".header_sign-up-btn > span")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("test123@email.com");
    driver.findElement(By.cssSelector(".form-content-container")).click();
    driver.findElement(By.id("firstName")).click();
    driver.findElement(By.id("firstName")).sendKeys("TopGTester");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("BlablaCar@123");
    driver.findElement(By.cssSelector(".right-side")).click();
    driver.findElement(By.id("password")).sendKeys("BlablaCar@123");
    driver.findElement(By.id("repeatPassword")).click();
    driver.findElement(By.id("repeatPassword")).sendKeys("BlablaCar@123");
    driver.findElement(By.cssSelector(".greenStyle")).click();
  }
}
